excel_mapping = {
    'Email':'B',
    'First Name': 'C',
    'Last Name': 'D',
    'Pre Profession':'F',
    'Major(s)':'G',
    'Minor(s)':'H',
    'Region':'I',
    'Hometown':'J',
    'Preference: Same Major': 'K',
    'Preference: Advising Style':'L',
    'Preference: Watching Movies':'M',
    'Preference: Eating Together':'N',
    'Preference: Study Sessions': 'O',
    'Preference: Sports':'P',
    'Preference: Staying In':'Q',
    'Preference: Going Downtown':'R',
    'Preference: Contact': 'S',
    'Preference: Weekend':'T',
    'Preference: Sudden Event':'U',
    'Preference: Personality1':'V',
    'Preference: Personality2':'W',
    'Preference: Personality3':'X',
    'Preference: Personality4':'Y',
    'Preference: Personality5':'Z',
    'Preference: Personality6':'AA',
    'Preference: Personality7':'AB',
    'Preference: Personality8':'AC'
}