
excel_mapping = {
    'Email':'C',
    'Name': 'B',
    'Pre Profession':'T',
    'Major(s)':'F',
    'Minor(s)':'U',
    'Region':'H',
    'Hometown':'I',
    'Preference: Same Major': 'P',
    'Preference: Advising Style':'Q',
    'Preference: Watching Movies':'J',
    'Preference: Eating Together':'K',
    'Preference: Study Sessions': 'L',
    'Preference: Sports':'M',
    'Preference: Staying In':'N',
    'Preference: Going Downtown':'O',
    'Preference: Contact': 'R',
    'Preference: Weekend':'AD',
    'Preference: Sudden Event':'AE',
    'Preference: Personality1':'V',
    'Preference: Personality2':'W',
    'Preference: Personality3':'X',
    'Preference: Personality4':'Y',
    'Preference: Personality5':'Z',
    'Preference: Personality6':'AA',
    'Preference: Personality7':'AB',
    'Preference: Personality8':'AC',
    'Rank1':'AF',
    'Rank2':'AG',
    'Rank3':'AH',
    'Rank4':'AI',
    'Rank5':'AJ'
}